### ISSUE TITLE
Add instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [EsmailELBoBDev2/EsmailELBoBDev2#1]
Hi @Metastem @SamantazFox @Bnyro @NoPlagiarism @httpjamesm @unixfox,
I pinged you here because I'm lazy to reply one by one on the issues. Treat this like a public letter if you well. 

You guys removed my instance without even a word or ping me to give me a chance to defend myself so first of all fuck you, there is no civilization about that. Blocking me all together without even hearing my thoughts, second I got hacked because of it so how come do you guys support free speech and same time shut me up. I did not offend someone in specific and yes as I know I have no way to know if someone is gay or not but these are my terms like them ok and if you do not then go away. Simple! Anyways here is my big reply: https://codeberg.org/LibRedirect/libredirect/issues/89#issuecomment-919797

Put in your mind, I did not offend anyone and you shut me without even giving me a chance to reply so thats my reply. if its cool then re-add my instance. I will be waiting your reply

**Comment by EsmailELBoBDev2** [comment]
https://github.com/zyachel/quetre/issues/107 https://github.com/libreddit/libreddit-instances/issues/81 https://github.com/zyachel/libremdb/issues/47 https://github.com/benbusby/whoogle-search/issues/1006 https://github.com/rramiachraf/dumb/issues/33 https://github.com/nesaku/BiblioReads/issues/8 too!

**Comment by Bnyro** [comment]
Good evening!

From our perspective, you're allowed to have any opinion about political things you want.
The thing of "supporting free speech" as you said would implicate that everyone is allowed to have the same chances and is welcomed the same way for doing what they want to on your services. We do really appreciate your efforts in hosting various services voluntary for the public use without benefiting financially from it, many open source projects like Piped wouldn't work without people like that.
From Piped's side, a code of conduct is going to be introduced soon that will be added to the repo and will ensure, everyone is welcome and invited to use the services in the same way, no matter of origin, religion, gender, etc.
Open source projects should never be a place of discrimination, and neither of political statements if possible. We support freedom for everyone, without any discrimination based on a person's properties.
We hope you'll understand our decision and wish you all the best.

Sincerely
@FireMasterK and @Bnyro

**Comment by EsmailELBoBDev2** [comment]
Hello @Bnyro (and others if you got same reply as him), thanks for taking the time to reply back!

Well, as much as I love your optimistic point of view. You gotta understand that it's a forbidden act in my religion so I will never change my opinion about the topic. And I did not offend anyone or really stopped anyone from using my instances. I'm just taking a stand and saying my opinion so as you and @MagicLike got the space to say you support LGBT I think it's my right to get same space to say my opinion about it too!! 

Your claim of me not welcoming everyone is false. Any gay can still access my service BUT I have my right to say my believes as long as I do not hurt or offend anyone in specific. 

And how you say you support free speech but push code of conduct that will conflict with me personally and my religion? Am I not allowed to defend me and my religion? (not in harm way ofc) so you just push it and I shut up or support it, I have no chance to refuse it?? 

I hope you reconsider it.

Thanks.

**Comment by FireMasterK** [comment]
> Your claim of me not welcoming everyone is false. Any gay can still access my service BUT I have my right to say my believes as long as I do not hurt or offend anyone in specific.

You're clearly offending the entire LGBTQ community by being racist against them.

> And how you say you support free speech but push code of conduct that will conflict with me personally and my religion? Am I not allowed to defend me and my religion? (not in harm way ofc) so you just push it and I shut up or support it, I have no chance to refuse it??

I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.

**Comment by NoPlagiarism** [comment]
About me & @Metastem:

Metastem has only one Instance list, and it's [WikiLess fork](https://github.com/Metastem/wikiless), where your instance isn't deleted [At least for now]

I am not maintaining any Instances list [manually](https://github.com/NoPlagiarism/frontend-instances-list), except [librarian](https://github.com/NoPlagiarism/frontend-instances-custom/tree/master/librarian) and kinda [WikiLess](https://github.com/NoPlagiarism/frontend-instances-custom/tree/master/wikiless). Both include ur instances, cuz they're just working. And not containing malicious code and own propaganda and/or lgbtq content bans

**Comment by NoPlagiarism** [comment]
War... [Gender War never changes](https://farside.link/piped/watch?v=rIIoKShHiSI)

**Comment by EsmailELBoBDev2** [comment]
> You're clearly offending the entire LGBTQ community by being racist against them.

I'm not offending anyone, I do not slur them or kill them. I simply reject what I see wrong in my beliefs. like vegans who gets mad when see someone eat meat... 

> I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.

And I would recommend giving you this to read: https://en.wikipedia.org/wiki/LGBT_people_and_Islam#Messengers_to_Lot it's straight from Quran 

Again, for the last damn time, I'm not targeting anybody I'm just rejecting the "act" that I see wrong in my religion and I even did not enforce my policy fully *yet*, lol.

**Comment by EsmailELBoBDev2** [comment]
> About me & @Metastem:
> 
> Metastem has only one Instance list, and it's [WikiLess fork](https://github.com/Metastem/wikiless), where your instance isn't deleted [At least for now]
> 
> I am not maintaining any Instances list [manually](https://github.com/NoPlagiarism/frontend-instances-list), except [librarian](https://github.com/NoPlagiarism/frontend-instances-custom/tree/master/librarian) and kinda [WikiLess](https://github.com/NoPlagiarism/frontend-instances-custom/tree/master/wikiless). Both include ur instances, cuz they're just working. And not containing malicious code and own propaganda and/or lgbtq content bans

I will never include malicious code. and about bans no, not either I believe in free internet. do whatever you want online. search for hot single gays in your area or not, I do not care about other people. I care about me and my opinion and my right to say it out loud and clear like other people when it comes to "supporting" 

PS: I'm more of god of war tbh

**Comment by EsmailELBoBDev2** [comment]
I want to say it's funny no one talked about this: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a#diff-aab9ddb6f6ada7ffa2ef1b9e8e8c60a8e91b365930b54f0dac6534945f600502R32 so you all fuzzy about lgbt but not this group... so I think Zionist are aliens ? or all of you suddenly care about Palestine and hate Israel?

guys if you are going to fight me at least fight for whole package and all groups not just "lgbt" it shows how much you guys are ignorant 

I bet on my both nuts that no one read my response even: https://codeberg.org/LibRedirect/libredirect/issues/89#issuecomment-919797

**Comment by FireMasterK** [comment]
> I'm not offending anyone, I do not slur them or kill them. I simply reject what I see wrong in my beliefs. like vegans who gets mad when see someone eat meat...

Just discriminating against anyone is considered offensive. You don't need to say bad things about (although you've clearly already done that) / cause harm to someone for this.

> I will never include malicious code. and about bans no, not either I believe in free internet. do whatever you want online. search for hot single gays in your area or not, I do not care about other people. I care about me and my opinion and my right to say it out loud and clear like other people when it comes to "supporting"

Only time will tell how long this stays the case... I think you're very well capable of thinking about censoring content/users based on your personal beliefs in the future.

> Again, for the last damn time, I'm not targeting anybody I'm just rejecting the "act" that I see wrong in my religion and I even did not enforce my policy fully yet, lol.

> I want to say it's funny no one talked about this: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a#diff-aab9ddb6f6ada7ffa2ef1b9e8e8c60a8e91b365930b54f0dac6534945f600502R32 so you all fuzzy about lgbt but not this group... so I think Zionist are aliens ? or all of you suddenly care about Palestine and hate Israel?

> guys if you are going to fight me at least fight for whole package and all groups not just "lgbt" it shows how much you guys are ignorant

I don't think you get the point here. Maintain your instances/services in a secular and non-discriminatory manner and I personally wouldn't have issues with reinstating your instance on Piped's instance list. I don't think a privacy policy or ToS page is the place for discussion of topics related to politics and religion. The problem I have here is you bringing up your outright deranged discrimination based on religion and political views to every user who wants to use your services.

**Comment by EsmailELBoBDev2** [comment]
Well, I already said my thoughts. Feel free to reinstate my instance or not.
___
> Only time will tell how long this stays the case... I think you're very well capable of thinking about censoring content/users based on your personal beliefs in the future.

Yeah, sure we will see. You have my words I will never censor anything in my instances like "lgbt" in wikiless. I even did not have the thought until @NoPlagiarism brought it. 
___
> I don't think you get the point here. Maintain your instances/services in a secular and non-discriminatory manner and I personally wouldn't have issues with reinstating your instance on Piped's instance list. I don't think a privacy policy or ToS page is the place for discussion of topics related to politics and religion. The problem I have here is you bringing up your outright deranged discrimination based on religion and political views to every user who wants to use your services.

No, I think you who do not get it. All of you got rage when I said no LGBT but no one even mentioned me blocking Zionists too. yes now you are saying I have to operate my instance in non discriminatory manner but the thing is ALL of you talk about me blocking LGBT, not single one talking about the other point in ToS. Do you understand me now? Unless discriminate against Zionists is non-discriminatory manner in your opinion.

**Comment by guybrushdent** [comment]
Your tactics of pointing to another discrimination is called "whataboutism".
Come on over kids and read all of Esmails statements - it's proper Fascist Playbook 101

**Comment by FireMasterK** [comment]
Will stop replying here from this point on as it's pointless.

Your instance will not be reinstated at this point of time. Thanks for your understanding!

**Comment by EsmailELBoBDev2** [comment]
> Your tactics of pointing to another discrimination is called "whataboutism". Come on over kids and read all of Esmails statements - it's proper Fascist Playbook 101

That does not change fact you only defend one group

But to reply, I think your tactic is called "The Bandwagon Fallacy"

**Comment by Ahwxorg** [comment]
I have given a read to your reply, and I do not sympathise with someone that is clearly discriminating a certain group of people. I think you should be free to have your personal opinion, but I, as a software developer, do not want to be assosiated with someone that's anti-LGBTQIA+.

**Comment by EsmailELBoBDev2** [comment]
Why can't you just accept me and I accept you? I mean I'm cool working with people who support LGBT because unlike you I do not block people who disagree with me. It's fucking simple.

**Comment by EsmailELBoBDev2** [comment]
blacklisting me by way or another will force me to either shutup or "accept" them (which will never happen btw) so it will force your opinion over me and I'm sure it's not free speech, do not you think?

Anyways do whatever you want guys, I responded.

**Comment by guybrushdent** [comment]
Esmail, perhaps you don't know about or care about a thing called tolerance paradox.
You should give these short sentences a read and then conclude where you stand in this. As someone that grew up in a intolerant environment I really advise you to, and change, if possible.
[Just a quick read](https://www.politicalempathyproject.org/blog-posts/karl-poppers-paradox-of-tolerance-and-what-it-teaches-us-about-political-polarization)

**Comment by EsmailELBoBDev2** [comment]
Meh, I will pass about reading. I do not care how many articles praise in LGBT because at the end of the day it's still a forbidden act in my religion. OK?

But to reply, so you say I must exclude it all or accept it as all is that what you say? can't I reject the act instead of rejecting the human as a whole? lol.

Like I reject all forbidden acts like eating pork or alcoholism. As you guys take the space in sports, conferences, social media posts and literally ALL places (even FOSS projects like mastodon to praise your point of view about LGBT is good) I think it's my right to take same places to say no I do not like it. so I took my space in my ToS and said it. Simple really.

No paradox because I do not reject the human itself but the act. if that gay guy knows it's a disease and willing to get cured then why not helping him/her out? 

I hope you understand my point of view

**Comment by guybrushdent** [comment]
Since being gay ain't no disease and queer/non-binary folk is part of mankind since the beginning and even part in animalkind (so basically every being) and you also pass on education, that doesn't mention LGBTQ+ in it's text, I'm sorry to break it to you:
I do not understand it.

I however accept your fascist behaviour and just hope you won't ever harm anyone - be on your way and I hope to meet you again in a more positive setting - shallah.
I'm glad I don't need your services.

**Comment by Ahwxorg** [comment]
> Why can't you just accept me and I accept you? I mean I'm cool working with people who support LGBT because unlike you I do not block people who disagree with me. It's fucking simple.

I do not block you, I am willing to discuss it. But I have my reasons. If you as me "Why can't you just accept me and I accept you?" I could counter-ask you "why don't you just accept queer people?". This is not the issue. The issue is that you are actively against a group of people who did (in my eyes) nothing wrong. I cannot change your opinion, clearly. I do not support your behaviour and do not want anything to do with it. Please stop bothering me, as it's pretty pointless at this point. Simple right?

PS: I am not saying that you should shut up, I just simply do not want your name on my git repository. Host Binternet or any other service if you want, I do not care.

**Comment by EsmailELBoBDev2** [comment]
Look, mankind or animal kind. It's numbers are so low in animal kind and It's not the normal or accepted in religions and even logical. if it's normal trust me we would have no problem to get biological kids when 2 men or 2 women get married. so it's not. Plus, accepted or not, I respect my religion and you gotta respect my point of view as I respect yours of defending LGBT. so why not just work together? but nope you have to force your opinion over me to work together or run away.

You know what, I'm glad you do not need my services. I'm happy not serving people who forces their opinions on others and make me throw away my beliefs and my religion to just accept what they accept.

**Comment by EsmailELBoBDev2** [comment]
> > Why can't you just accept me and I accept you? I mean I'm cool working with people who support LGBT because unlike you I do not block people who disagree with me. It's fucking simple.
> 
> I do not block you, I am willing to discuss it. But I have my reasons. If you as me "Why can't you just accept me and I accept you?" I could counter-ask you "why don't you just accept queer people?". This is not the issue. The issue is that you are actively against a group of people who did (in my eyes) nothing wrong. I cannot change your opinion, clearly. I do not support your behaviour and do not want anything to do with it. Please stop bothering me, as it's pretty pointless at this point. Simple right?
> 
> PS: I am not saying that you should shut up, I just simply do not want your name on my git repository. Host Binternet or any other service if you want, I do not care.

Okay, I still reject the act itself not the human who does it. I think already said that.

**Comment by Ahwxorg** [comment]
I am not throwing away your beliefs, nor am I trying to.

I like to think that one should not bother another with their religon. I've made my point clear.

**Comment by EsmailELBoBDev2** [comment]
> I am not throwing away your beliefs, nor am I trying to.
> 
> I like to think that one should not bother another with their religon. I've made my point clear.

this reply was not for you btw~ https://github.com/EsmailELBoBDev2/EsmailELBoBDev2/issues/1#issuecomment-1559134586

**Comment by WAZAAAAA0** [comment]
I don't have a horse in this race but I just wanted to chime in.

For me the instance maintainer might as well be Jack the Ripper himself I don't give a damn, the more instances the merrier. The privacy policy has 0 value and it could as well ask for my soul for all I care.

It's just funny to me how the anti-jew part could stay for the longest time, but the moment you touch the gays in IT you get delisted with the greatest of ease 😂

EDIT: temporary backup of the `pri-tos.md` for reference <https://webcache.googleusercontent.com/search?q=cache:https://github.com/EsmailELBoBDev2/upptime/blob/master/pri-tos.md>

**Comment by EsmailELBoBDev2** [comment]
> It's just funny to me how the anti-jew part could stay for the longest time, but the moment you touch the gays in IT you get delisted with the greatest of ease joy

No no, I think they support Palestine. 

> EDIT: temporary backup of the `pri-tos.md` for reference https://webcache.googleusercontent.com/search?q=cache:https://github.com/EsmailELBoBDev2/upptime/blob/master/pri-tos.md

Thanks for the link but I already got it on my gitea. https://git.esmailelbob.xyz/esmail/upptime/src/branch/master/pri-tos.md

**Comment by Ahwxorg** [comment]
I - in all fairness - did not look into your profile enough to see that. If I would've seen it, you would not be accepted. Once the issue was opened and I saw the commit, I just removed you. Simple as that. Please close any further issue.

**Comment by privacytime101** [comment]
> Hi @Metastem @SamantazFox @Bnyro @NoPlagiarism @httpjamesm @unixfox, I pinged you here because I'm lazy to reply one by one on the issues. Treat this like a public letter if you well.

> so first of all fuck you

No one's going to take you seriously if you open your letter by insulting all of us. I especially don't appreciate you pinging james, since removing you from AO's instance list was something we both deemed necessary. 

Had I known about your stances earlier, you would never have been added. I even helped you with a hosting issue on Matrix a few months back, as I believed you were a respectful and valued contributor to the FOSS hosting community. That couldn't have been further from the truth.

You can't restrict FOSS instances to only certain groups of people and expect to be welcomed here. It's a hugely disrespectful action against groups of people that are already under pressure, and it's an attack on free and open-source privacy as well. 

Educate yourself.

**Comment by EsmailELBoBDev2** [comment]
> , as I believed you were a respectful and valued contributor to the FOSS hosting community.

Nah, pretty much I'm still same respectful member.  No one talked about mastodon forcing their political views about LGBT (that all instances should welcome them) but all of you got mad about me restricting them. It's same thing, Mastodon added political views and forced it and I did the same but nope. Mastodon is welcome to do so because all of you got same opinion but me? HOW DARE I RESPECT MY RELIGION? 

If you are going to remove me, then remove all people who involved LGBT into everything even sports with lgbt captain badge

**Comment by EsmailELBoBDev2** [comment]
> I - in all fairness - did not look into your profile enough to see that. If I would've seen it, you would not be accepted. Once the issue was opened and I saw the commit, I just removed you. Simple as that. Please close any further issue.

Exactly no one reads these days

**Comment by Ahwxorg** [comment]
> > , as I believed you were a respectful and valued contributor to the FOSS hosting community.
> 
> Nah, pretty much I'm still same respectful member. No one talked about mastodon forcing their political views about LGBT (that all instances should welcome them) but all of you got mad about me restricting them. It's same thing, Mastodon added political views and forced it and I did the same but nope. Mastodon is welcome to do so because all of you got same opinion but me? HOW DARE I RESPECT MY RELIGION?
> 
> If you are going to remove me, then remove all people who involved LGBT into everything even sports with lgbt captain badge

I (and probably we) have made it very clear that I (again and probably we) do not respect you actively not accepting a group of people. Mastodon is including them. It's a different thing. Like someone a little above this reply said: educate yourself. I am blocking you since I do not feel like having my time wasted by you.

**Comment by EsmailELBoBDev2** [comment]
> > > , as I believed you were a respectful and valued contributor to the FOSS hosting community.
> > 
> > 
> > Nah, pretty much I'm still same respectful member. No one talked about mastodon forcing their political views about LGBT (that all instances should welcome them) but all of you got mad about me restricting them. It's same thing, Mastodon added political views and forced it and I did the same but nope. Mastodon is welcome to do so because all of you got same opinion but me? HOW DARE I RESPECT MY RELIGION?
> > If you are going to remove me, then remove all people who involved LGBT into everything even sports with lgbt captain badge
> 
> I (and probably we) have made it very clear that I (again and probably we) do not respect you actively not accepting a group of people. Mastodon is including them. It's a different thing. Like someone a little above this reply said: educate yourself. I am blocking you since I do not feel like having my time wasted by you.

I (and probably we) have made it very clear that I (again and probably we) will never my ToS.

And no, it's LITERAL same thing. mastodon got the right to involve political opinions and include them based on their beliefs so I get the same right to exclude them based on my beliefs. It's simple. 

And no, the one who should be educated (or group rather) is LGBT because I got doxxed and hacked. Just because I said I do not support them. Like really? Mafia? Is that freespeech, damn. so nope, I won't back down it got so personal, so religion and logic aside. I won't change my ToS. 

So all of you feel free to remove my instances because we got different point of views (silly reason, but whatever) I write a comment defending my beliefs and without insulting anyone but I get all the heat and them doxxing me? no it's heroic for them. You guys are really weird, that's all I'm going to say.

**Comment by EsmailELBoBDev2** [comment]
Also, Can we just agree to disagree? I will not back down and you won't list it back so just shut-up. Because I got headache from this, lol.

**Comment by qasourabastm** [comment]
> I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.

do you think we will change our religion just to fit you? we never attacked LGBTQ thingies ,yet you force that crap on us and our children and you think we will accept you like that?

**Comment by qasourabastm** [comment]
> Since being gay ain't no disease and queer/non-binary folk is part of mankind since the beginning and even part in animalkind (so basically every being)
who said its not disease? 
,wow are making your whole point on some animals? i guess rape is okay then
fucking animals

**Comment by qasourabastm** [comment]
> It's just funny to me how the anti-jew part could stay for the longest time
its not anti jew you idiot
Zionist is not the Jewish religion
many many jew in -and oustide- palstine and Israel it self are against Zionist

**Comment by nepnep39** [comment]
> Hi @Metastem @SamantazFox @Bnyro @NoPlagiarism @httpjamesm @unixfox, I pinged you here because I'm lazy to reply one by one on the issues. Treat this like a public letter if you well.
> 
> You guys removed my instance without even a word or ping me to give me a chance to defend myself so first of all fuck you, there is no civilization about that. Blocking me all together without even hearing my thoughts, second I got hacked because of it so how come do you guys support free speech and same time shut me up. I did not offend someone in specific and yes as I know I have no way to know if someone is gay or not but these are my terms like them ok and if you do not then go away. Simple! Anyways here is my big reply: https://codeberg.org/LibRedirect/libredirect/issues/89#issuecomment-919797
> 
> Put in your mind, I did not offend anyone and you shut me without even giving me a chance to reply so thats my reply. if its cool then re-add my instance. I will be waiting your reply

You guys removed my instance without a word
Didn't even ping me, that's so absurd
You think you can silence me, well f**k you
You don't respect free speech, you're just a bunch of fools

You blocked me without hearing my thoughts
And then I got hacked, thanks a lot
I didn't offend anyone, I just spoke my mind
If you don't like it, then leave me behind

You can't tell who's gay or not by their name
But these are my terms, I'm not here to play games
If you agree with me, then we're cool
If you don't, then you're a tool

Here's my big reply, read it and weep
You can't handle the truth, it's too deep
You're just a bunch of hypocrites and liars
You can't stop me, I'm on fire

WHO WON? WHO'S NEXT? YOU DECIDE!

**Comment by WAZAAAAA0** [comment]
> its not anti jew you idiot Zionist is not the Jewish religion many many jew in -and oustide- palstine and Israel it self are against Zionist

OY VEY!!

**Comment by Tosoju** [comment]
> WHO WON? WHO'S NEXT? YOU DECIDE!

...did you just post an Bing AI-generated Epic Rap Battle of History on a thread about homophobia and religion

**Comment by nepnep39** [comment]
> ...did you just post an Bing AI-generated Epic Rap Battle of History on a thread about homophobia and religion

yeah

**Comment by 4lkanoid** [comment]
> > ...did you just post an Bing AI-generated Epic Rap Battle of History on a thread about homophobia and religion
> 
> yeah

outstanding bars i must say

**Comment by guybrushdent** [comment]
> > I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.
> 
> do you think we will change our religion just to fit you? we never attacked LGBTQ thingies ,yet you force that crap on us and our children and you think we will accept you like that?

We force nothing - you are the ones discriminating - we don't accept discrimination - go figure

**Comment by EsmailELBoBDev2** [comment]
Hi, so long. Got busy. anyway back to our mini fight.
___
> > > I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.
> > 
> > 
> > do you think we will change our religion just to fit you? we never attacked LGBTQ thingies ,yet you force that crap on us and our children and you think we will accept you like that?
> 
> We force nothing - you are the ones discriminating - we don't accept discrimination - go figure

I force nothing, I can force it trust me. Remove all lgbt mentions from my instances based on URL regex or anything but I do not and will not because I believe in free internet. In fact you are forcing your opinions on me by removing my instances one by one or hacking my accounts and ddosing my servers, thinking I will back down. You do not see me blocking you or other "supporters" but what all of you did? @magiclike blocked me and fighting to get me removed from all instances just because we did not get same opinion. Did I block him? or ddosed his severs? or doxxed him? so think twice and see who is forcing their opinions...

**Comment by Metastem** [comment]
> Hi, so long. Got busy. anyway back to our mini fight.
> 
> > > > I'd recommend giving https://www.hrc.org/resources/stances-of-faiths-on-lgbt-issues-islam a read. Everyone is expected to follow the code of conduct, which will be strictly enforced. If you don't like that, you are free to find another community which shares your beliefs. We try to be as secular as possible, and expect everyone to keep things the same way.
> > > 
> > > 
> > > do you think we will change our religion just to fit you? we never attacked LGBTQ thingies ,yet you force that crap on us and our children and you think we will accept you like that?
> > 
> > 
> > We force nothing - you are the ones discriminating - we don't accept discrimination - go figure
> 
> I force nothing, I can force it trust me. Remove all lgbt mentions from my instances based on URL regex or anything but I do not and will not because I believe in free internet. In fact you are forcing your opinions on me by removing my instances one by one or hacking my accounts and ddosing my servers, thinking I will back down. You do not see me blocking you or other "supporters" but what all of you did? @MagicLike blocked me and fighting to get me removed from all instances just because we did not get same opinion. Did I block him? or ddosed his severs? or doxxed him? so think twice and see who is forcing their opinions...

你们教徒是阻碍社会变革最激进的力量，剥夺右派、自由派和反动派的言论自由？我绝对支持lol

**Comment by tuxayo** [comment]
@EsmailELBoBDev2  

> but no one even mentioned me blocking Zionists too.  yes now you are saying I have to operate my instance in non discriminatory manner but the thing is ALL of you talk about me blocking LGBT, not single one talking about the other point in ToS. Do you understand me now? Unless discriminate against Zionists is non-discriminatory manner in your opinion.

Yes forbidding Zionists is non-discriminatory. It wouldn't be the same it you would have wrote about forbidding Jewish people. Is like the difference between forbidding white people or only white supremacists.

It's not the same as forbidding LGBT people. This is like if another instance would forbid Muslim people. That would be the same issue and we would find a number of projects and users that oppose islamophobia and racism that wouldn't like to list such an instance. And there for the current issue, you have a number of projects and users that oppose discrimination based on sexual orientation and gender identity.

> I have to operate my instance in non discriminatory manner

You can forbid racism, islamophobia, antisemitism, sexism, white supremacy, Zionism, nazism. And it wouldn't be discriminatory IMHO. You would be basically forbidding discrimination so that's not discrimination.
The various sexual orientations and gender identities that you oppose are not about discrimination. Just like being a heterosexual isn't about discrimination, it's about being heterosexual, that all.
However, something like heterosexual supremacy is about discrimination.

**Comment by EsmailELBoBDev2** [comment]
> @EsmailELBoBDev2
> 
> > but no one even mentioned me blocking Zionists too.  yes now you are saying I have to operate my instance in non discriminatory manner but the thing is ALL of you talk about me blocking LGBT, not single one talking about the other point in ToS. Do you understand me now? Unless discriminate against Zionists is non-discriminatory manner in your opinion.
> 
> Yes forbidding Zionists is non-discriminatory. It wouldn't be the same it you would have wrote about forbidding Jewish people. Is like the difference between forbidding white people or only white supremacists.
> 
> It's not the same as forbidding LGBT people. This is like if another instance would forbid Muslim people. That would be the same issue and we would find a number of projects and users that oppose islamophobia and racism that wouldn't like to list such an instance. And there for the current issue, you have a number of projects and users that oppose discrimination based on sexual orientation and gender identity.
> 
> > I have to operate my instance in non discriminatory manner
> 
> You can forbid racism, islamophobia, antisemitism, sexism, white supremacy, Zionism, nazism. And it wouldn't be discriminatory IMHO. You would be basically forbidding discrimination so that's not discrimination. The various sexual orientations and gender identities that you oppose are not about discrimination. Just like being a heterosexual isn't about discrimination, it's about being heterosexual, that all. However, something like heterosexual supremacy is about discrimination.

Cool finally someone talk out of their brain instead of yelling or insulting.
___
Look, I get your point. blocking Zionists or Nazi people is ok because they are bad people already. But the thing is that I'm Muslim and I follow my religion and in my religion the **act** not the person is forbidden so I think it's my right to express my refusal as people get the chance to express their acceptance. I did not insult someone in specific, or target attack or anything. I'm simply expressing my thoughts according to my religion. I do not forbid the person him/her-self. So I think it's simple, is not it? And those projects should learn to live with people who got different opinions.

Beside religion reasons, it's still not logical. How come someone wakes up and be woman suddenly? sure there are some messed up hormones and that's why there is therapy for it to get it back to biological level so if you are a man you get man hormones and fix it. but nope! people always abuse stuff.

So logical or religious reasons. LGBT seems dumb to me (by dumb I mean the act and people who refuse to see it's true nature, a mental/physiological illness) and  I will never take my words back.
___
PS: I will not support LGBT 
PS of PS: If you want to continue this grown up chitchat and discuss with me the points about logical or mental illness then why not? but know most likely I wont get convinced because no matter what, it's still forbidden act in my religion.

**Comment by WAZAAAAA0** [comment]
Today marks the day of the death of the last surviving nitter instance, `nitter.esmailelbob.xyz`

I've been using multiple randomly rotated instances since 2021 and this happened to be the one with the most consistently high uptime and bandwidth in my experience.

And you guys wanted to delist this dude for... politics? lol. lmao even.

**Comment by EsmailELBoBDev2** [comment]
its dead since 2023 because of HDD issues in server and I will work again to see if there is option to bring it and all other instances back (rate limit, I hate it)
